name: Run tests for `MariaDB` only
on:
  push:
    branches:
      - read_from_master_if_model_uses_another_database
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        x:
          - gemfile: 'rails_5.0'
            ruby: '2.4.7'
          - gemfile: 'rails_5.1'
            ruby: '2.4.7'
          - gemfile: 'rails_5.2'
            ruby: '2.4.7'
          - gemfile: 'rails_5.0'
            ruby: '2.5.6'
          - gemfile: 'rails_5.1'
            ruby: '2.5.6'
          - gemfile: 'rails_5.2'
            ruby: '2.5.6'
          - gemfile: 'rails_5.2'
            ruby: '2.6.3'
          - gemfile: 'rails_5.2'
            ruby: '2.7.4'
          - gemfile: 'rails_6.0'
            ruby: '2.7.4'
          - gemfile: 'rails_6.1'
            ruby: '2.7.4'
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.x.gemfile }}.gemfile
    steps:
      - uses: actions/checkout@v2
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3306
          mysql root password: password
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3308
          mysql root password: password
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.x.ruby }}
          bundler-cache: true
          cache-version: 2
      - run: bundle exec appraisal ${{ matrix.x.gemfile }} rake test
